In [1]:
# importing the necessaries
import sys
import os
# Adding the root to the path to use utils folder
sys.path.append(os.path.abspath(os.path.join('..')))

from utils.db_utils import run_query 
from utils.custom_plots import distribution_plot, outlier_plot, schema_diagram

<div class="alert alert-block alert-success">

### **First lets take a look at how tables are connected in this database**

In [2]:
database_diagram=schema_diagram(run_query_fn=run_query,
                                layout='circular',
                                edge_labels='always',
                                title='Football database schema')

database_diagram

d:\Data_Analysis_BC\Projects\Football-EDA\utils\db_utils.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn, params=params)

<div class="alert alert-block alert-success">

#### **we have 6 tables in this database that are connected with different foreign keys**
- as we can see in the plot the only independent table in the database is 'Competitions' 
- all tables other then 'Competitions' are dependent to at least 1 table 
- tables 'appearances' and 'game_events' are referenced by 0 tables

<div class="alert alert-block alert-success">


# **Now lets look at each table in more depth** 

**1-what is their purpose and what are they features(columns)?**

**2-how many null or missing values they have?**

**3-what is their distribution?**

**4-how their outliers are layedout?**

**5-what are the cleaning opportunities?**

<div class="alert alert-block alert-success">

## **Table: Competition**

In [3]:
competitions_summary = run_query('select * from competitions')

competitions_summary.head(10)

d:\Data_Analysis_BC\Projects\Football-EDA\utils\db_utils.py:19: UserWarning:

pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.

  competition_id                           name             type country_name
0            CIT                      italy-cup     domestic_cup        Italy
1           NLSC           johan-cruijff-schaal            other  Netherlands
2            GRP                kypello-elladas     domestic_cup       Greece
3           POSU  supertaca-candido-de-oliveira            other     Portugal
4           RUSS              russian-super-cup            other       Russia
5            SUC                      supercopa            other        Spain
6            DK1                    superligaen  domestic_league      Denmark
7            ES1                         laliga  domestic_league        Spain
8            FR1                        ligue-1  domestic_league       France
9            IT1                        serie-a  domestic_league        Italy

In [4]:
competitions_summary.describe()

       competition_id       name             type country_name
count              43         43               43           36
unique             43         43                4           14
top               CIT  italy-cup  domestic_league      England
freq                1          1               14            4

In [5]:
competitions_summary.info()

<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   competition_id  43 non-null     str
 1   name            43 non-null     str
 2   type            43 non-null     str
 3   country_name    36 non-null     str
dtypes: str(4)
memory usage: 1.5 KB

In [6]:
# finding nulls :
competitions_summary[competitions_summary.isnull().any(axis=1)]

,competition_id,name,type,country_name
36,USC,uefa-super-cup,other,NaN
37,EL,europa-league,international_cup,NaN
38,ELQ,europa-league-qualifikation,international_cup,NaN
39,ECLQ,uefa-europa-conference-league-qualifikation,international_cup,NaN
40,CL,uefa-champions-league,international_cup,NaN
41,KLUB,fifa-klub-wm,other,NaN
42,CLQ,uefa-champions-league-qualifikation,international_cup,NaN

In [ ]:
id_cols = ["competition_id", 'name']

competitions_dist = distribution_plot(competitions_summary, n_cols=2, title='Competitions Distribution',top_n_categories=20, ignore_cols=id_cols)
competitions_dist

<div class="alert alert-block alert-success">

### **Competitions summary**: 
this table stores the data of each football competition

### **columns**:
**competition_id:** unique string id of the competition

**name:** full name of the competition

**type:** type of the competition , we have only 4 types(domestic, international , ...)

**country_name:** name of the country where competition belongs to.(it has 7 null values for competitions that are international)

### **no opportunity for cleaning**

<div class="alert alert-block alert-success">

## **Table: Clubs**

In [8]:
clubs_summary = run_query('select * from clubs')
clubs_summary.head(10)

d:\Data_Analysis_BC\Projects\Football-EDA\utils\db_utils.py:19: UserWarning:

pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.

,club_id,name,domestic_competition_id,squad_size,foreigners_number,national_team_players,stadium_name,stadium_seats,net_transfer_record
0,2578,Saint Johnstone Football Club,SC1,25,16,2,McDiarmid Park,10696,+-0
1,2727,Oud-Heverlee Leuven,BE1,29,16,2,King Power at Den Dreef Stadion,10020,+300k
2,28643,SK Beveren,BE1,27,16,3,Freethielstadion,13290,-350k
3,2990,Académica Coimbra,PO1,26,6,0,Estádio Cidade de Coimbra,29744,+150k
4,3057,Royal Standard Club de Liège,BE1,27,18,10,Maurice Dufrasne Stadion,27670,+3.11m
5,3690,SKA Khabarovsk,RU1,27,4,0,Lenin Stadion,15200,-93k
6,4795,FC Ingolstadt 04,L1,28,8,1,Audi Sportpark,15800,+1.55m
7,511,Dundee Football Club,SC1,26,16,3,Kilmac Stadium at Dens Park,11850,+-0
8,5358,SD Huesca,ES1,24,8,2,El Alcoraz,9128,+1.43m
9,603,Cardiff City,GB1,28,24,8,Cardiff City Stadium,33280,-655k

In [9]:
clubs_summary.describe()

,club_id,squad_size,foreigners_number,national_team_players,stadium_seats
count,426.000000,426.000000,426.000000,426.000000,426.000000
mean,5314.525822,24.288732,10.992958,4.866197,24299.420188
std,11752.013818,8.735255,6.617798,4.982646,17192.103990
min,3.000000,0.000000,0.000000,0.000000,1312.000000
25%,421.000000,24.000000,6.000000,1.000000,11024.500000
50%,1139.500000,27.000000,12.000000,3.000000,20046.000000
75%,3415.750000,29.000000,16.000000,8.000000,32448.000000
max,83678.000000,41.000000,26.000000,21.000000,81365.000000

In [10]:
clubs_summary.info()

<class 'pandas.DataFrame'>
RangeIndex: 426 entries, 0 to 425
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   club_id                  426 non-null    int64
 1   name                     426 non-null    str
 2   domestic_competition_id  426 non-null    str
 3   squad_size               426 non-null    int64
 4   foreigners_number        426 non-null    int64
 5   national_team_players    426 non-null    int64
 6   stadium_name             426 non-null    str
 7   stadium_seats            426 non-null    int64
 8   net_transfer_record      426 non-null    str
dtypes: int64(5), str(4)
memory usage: 30.1 KB

In [11]:
ignore_list = ['name', 'club_id', 'stadium_name']
clubs_dist = distribution_plot(clubs_summary, title="Clubs Distribution", n_cols=3, ignore_cols=ignore_list)
clubs_dist

In [12]:
clubs_boxplot = outlier_plot(df=clubs_summary, ignore_list=ignore_list, title="Outliers layout for clubs table", orientation='vertical', n_cols=4)
clubs_boxplot

<div class="alert alert-block alert-success">

### **clubs summary**: 
this table stores the data of each football club

### **columns**:
**club_id:** unique id of each football club

**name:** full name of the football club

**domestic_competition_id:** the domestic competition id of the club 

**squad_size:** size of the whole football team (this column has the most outliers)

**foreigners_number:** number of foreign people in the team

**national_team_players:** number of players that are in the international team of their own country

**stadium_name:** name of the owned stadium of the club 

**stadium_seats:** number of seats in the club's stadium 

**net_transfer_record:** net value of the club

### **opportunity for cleaning/transforming**:
- transform the net_transfer_record column to show the pure number without any + ,- ,k or m symbol

<div class="alert alert-block alert-success">

## **Table: Players**

In [27]:
players_summary = run_query('select * from players')
players_summary.head(10)

d:\Data_Analysis_BC\Projects\Football-EDA\utils\db_utils.py:19: UserWarning:

pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.

,player_id,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,contract_expiration_date
0,569140,290,lassine-sinayoko,NaN,Bamako,NaN,1999-12-08,Right Winger,Attack,right,186.0,2025-06-30
1,569368,44,kelian-nsona,NaN,Ivry-sur-Seine,NaN,2002-05-11,Right Winger,Attack,right,189.0,2026-06-30
2,569385,1158,adil-aouchiche,NaN,Le Blanc-Mesnil,NaN,2002-07-15,Attacking Midfield,Midfield,right,181.0,2026-06-30
3,607809,11127,ilya-bykovskiy,NaN,"Lyubertsy, Moskau Oblast",NaN,2001-02-16,Left-Back,Defender,left,177.0,2024-06-30
4,627221,720,gabriel-veron,NaN,Assu,NaN,2002-09-03,Right Winger,Attack,right,176.0,2027-06-30
5,627294,1050,fer-nino,NaN,Rota,NaN,2000-10-24,Centre-Forward,Attack,right,191.0,2026-06-30
6,650519,2424,lucas-barros,NaN,Rio de Janeiro,NaN,1999-08-21,Left-Back,Defender,left,180.0,2024-06-30
7,655835,989,christian-saydee,NaN,London,NaN,2002-05-10,Centre-Forward,Attack,right,184.0,2026-06-30
8,668184,150,quique-fernandez,NaN,Trebujena,NaN,2003-09-16,Defensive Midfield,Midfield,left,177.0,2024-06-30
9,669312,83678,yevgeniy-ryazantsev,NaN,Kyiv,NaN,2002-01-28,Right Winger,Attack,right,186.0,2024-06-30

In [14]:
players_summary.describe()

          player_id  current_club_id  height_in_cm
count  1.536000e+04     15360.000000  14363.000000
mean   4.372485e+05      5195.039258    182.625009
std    2.680993e+05     12220.348699      7.162323
min    2.857000e+03         3.000000     18.000000
25%    2.139785e+05       385.000000    178.000000
50%    4.101985e+05      1041.000000    183.000000
75%    6.284945e+05      3060.000000    188.000000
max    1.240762e+06     83678.000000    206.000000

In [15]:
players_summary.info()

<class 'pandas.DataFrame'>
RangeIndex: 15360 entries, 0 to 15359
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player_id                 15360 non-null  int64
 1   current_club_id           15360 non-null  int64
 2   player_code               15360 non-null  str
 3   country_of_birth          13598 non-null  str
 4   city_of_birth             14113 non-null  str
 5   country_of_citizenship    14782 non-null  str
 6   date_of_birth             15354 non-null  object
 7   sub_position              15329 non-null  str
 8   position                  15329 non-null  str
 9   foot                      14384 non-null  str
 10  height_in_cm              14363 non-null  float64
 11  contract_expiration_date  12928 non-null  object
dtypes: float64(1), int64(2), object(2), str(7)
memory usage: 1.4+ MB

In [16]:
# we have some missing data which is ok

In [25]:
ignore_list=['player_id', 'current_club_id', 'country_of_citizenship', 'city_of_birth', 'contract_expiration_date', 'player_code', 'date_of_birth']
players_dist = distribution_plot(players_summary, ignore_cols=ignore_list,title='Players Distribution', n_cols=2)
players_dist

In [36]:
# height distribution is highly skewed because of a player with 18 cm of height XD
players_summary[players_summary['height_in_cm'].between(15, 20)]

,player_id,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,contract_expiration_date
11525,592398,40,aissa-boudechicha,NaN,Medjana,Algeria,2000-04-13,Left-Back,Defender,left,18.0,2023-06-30
12206,628490,2687,genar-fornes,Spain,Barcelona,Spain,2000-01-17,Left-Back,Defender,left,18.0,2023-06-30

In [ ]:
# these are real players but they are definitely not 18 centimeters