In [11]:
import sys
import os
# Adding the root to the path to use utils folder
sys.path.append(os.path.abspath(os.path.join('..')))

from utils.db_utils import run_query 
from utils.custom_plots import distribution_plot

<div class="alert alert-block alert-success">


### In this notebook we are going to have a first look at the tables of this database

**1-what is their purpose and what are they features(columns)?**

**2-what is their relation and how they are connected?**

**3-how many null or missing values they have?**

**4-what is their distribution? are they normal?**

**5-how their outliers are layedout?**

**6-what are the cleaning opportunities?**

<div class="alert alert-block alert-success">

# Table: Competition

In [12]:
competitions_summary = run_query('select * from competitions')

competitions_summary.head(10)

d:\Data_Analysis_BC\Projects\Football-EDA\utils\db_utils.py:19: UserWarning:

pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.

  competition_id                           name             type country_name
0            CIT                      italy-cup     domestic_cup        Italy
1           NLSC           johan-cruijff-schaal            other  Netherlands
2            GRP                kypello-elladas     domestic_cup       Greece
3           POSU  supertaca-candido-de-oliveira            other     Portugal
4           RUSS              russian-super-cup            other       Russia
5            SUC                      supercopa            other        Spain
6            DK1                    superligaen  domestic_league      Denmark
7            ES1                         laliga  domestic_league        Spain
8            FR1                        ligue-1  domestic_league       France
9            IT1                        serie-a  domestic_league        Italy

In [13]:
competitions_summary.describe()

       competition_id       name             type country_name
count              43         43               43           36
unique             43         43                4           14
top               CIT  italy-cup  domestic_league      England
freq                1          1               14            4

In [14]:
competitions_summary.info()

<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   competition_id  43 non-null     str
 1   name            43 non-null     str
 2   type            43 non-null     str
 3   country_name    36 non-null     str
dtypes: str(4)
memory usage: 1.5 KB

In [15]:
# finding nulls :
competitions_summary[competitions_summary.isnull().any(axis=1)]

,competition_id,name,type,country_name
36,USC,uefa-super-cup,other,NaN
37,EL,europa-league,international_cup,NaN
38,ELQ,europa-league-qualifikation,international_cup,NaN
39,ECLQ,uefa-europa-conference-league-qualifikation,international_cup,NaN
40,CL,uefa-champions-league,international_cup,NaN
41,KLUB,fifa-klub-wm,other,NaN
42,CLQ,uefa-champions-league-qualifikation,international_cup,NaN

In [16]:
id_cols = ["competition_id", 'name']

competitions_dist = distribution_plot(competitions_summary, n_cols=2, title='Competitions Distribution',top_n_categories=20, ignore_cols=id_cols)
competitions_dist

<div class="alert alert-block alert-success">

## Competitions summary: 
**this table stores data of each football competition**

### columns:
**competition_id:** unique string id of the competition

**name:** full name of the competition

**type:** type of the competition , we have only 4 types(domestic, international , ...)

**country_name:** name of the country where competition belongs to.(it has 7 null values for competitions that are international)

#### no opportunity for cleaning

<div class="alert alert-block alert-success">

# Table: Clubs

In [17]:
clubs_summary = run_query('select * from clubs')
clubs_summary.head(10)

d:\Data_Analysis_BC\Projects\Football-EDA\utils\db_utils.py:19: UserWarning:

pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.

,club_id,name,domestic_competition_id,squad_size,foreigners_number,national_team_players,stadium_name,stadium_seats,net_transfer_record
0,2578,Saint Johnstone Football Club,SC1,25,16,2,McDiarmid Park,10696,+-0
1,2727,Oud-Heverlee Leuven,BE1,29,16,2,King Power at Den Dreef Stadion,10020,+300k
2,28643,SK Beveren,BE1,27,16,3,Freethielstadion,13290,-350k
3,2990,Académica Coimbra,PO1,26,6,0,Estádio Cidade de Coimbra,29744,+150k
4,3057,Royal Standard Club de Liège,BE1,27,18,10,Maurice Dufrasne Stadion,27670,+3.11m
5,3690,SKA Khabarovsk,RU1,27,4,0,Lenin Stadion,15200,-93k
6,4795,FC Ingolstadt 04,L1,28,8,1,Audi Sportpark,15800,+1.55m
7,511,Dundee Football Club,SC1,26,16,3,Kilmac Stadium at Dens Park,11850,+-0
8,5358,SD Huesca,ES1,24,8,2,El Alcoraz,9128,+1.43m
9,603,Cardiff City,GB1,28,24,8,Cardiff City Stadium,33280,-655k

In [18]:
clubs_summary.describe()

,club_id,squad_size,foreigners_number,national_team_players,stadium_seats
count,426.000000,426.000000,426.000000,426.000000,426.000000
mean,5314.525822,24.288732,10.992958,4.866197,24299.420188
std,11752.013818,8.735255,6.617798,4.982646,17192.103990
min,3.000000,0.000000,0.000000,0.000000,1312.000000
25%,421.000000,24.000000,6.000000,1.000000,11024.500000
50%,1139.500000,27.000000,12.000000,3.000000,20046.000000
75%,3415.750000,29.000000,16.000000,8.000000,32448.000000
max,83678.000000,41.000000,26.000000,21.000000,81365.000000

In [19]:
clubs_summary.info()

<class 'pandas.DataFrame'>
RangeIndex: 426 entries, 0 to 425
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   club_id                  426 non-null    int64
 1   name                     426 non-null    str
 2   domestic_competition_id  426 non-null    str
 3   squad_size               426 non-null    int64
 4   foreigners_number        426 non-null    int64
 5   national_team_players    426 non-null    int64
 6   stadium_name             426 non-null    str
 7   stadium_seats            426 non-null    int64
 8   net_transfer_record      426 non-null    str
dtypes: int64(5), str(4)
memory usage: 30.1 KB

In [21]:
clubs_dist = distribution_plot(clubs_summary, title="Clubs Distribution", n_cols=3)
clubs_dist